### ISSUE TITLE
Grav - Machine Theme - Home Page Clients Module

### ISSUE THREAD

**Issue by f1209** [Sommerregen/grav-theme-machine#1]
I have a couple of issues with the Machine Theme on Grav:

Homepage - Clients Module

/home/_clients/mirem-ipsum-usa client
1. Markup does not seem to work - I cannot get line breaks 
2. I edited the title 'Kind words from clients' to 'Words of a Poet' but the change does not 
3. When I create a new module - the page defaults to being a blog post and not a client module
4. The quote box around the comments - I do not know where to adjust the css to fit around the quote well

If anyone could help, that would be great. Thank you.

Notes about me:

Not a coder
Know enough to locally edit and file and upload via ftp
Using Grav so I can do easy CMS updates
If something is not working, it may be me not knowing what I am doing

Page I am editing is www.sevensistersroad.com
php 5.6

**Comment by Sommerregen** [comment]
Hi @f1209 ,

I'll see how I can help you. Converning
1. What does not work? Usually you just type in Markdown formatted content. The **Admin plugin** can help you here. For getting linebreaks you need **two** newlines instead of just one.
2. Usually if you change the title, your page should have new title, too. There are however some settings, why you don't see the change (which are mostly for beginners not obvious). i) You may check that you copied the demo content frome [here](https://github.com/Sommerregen/grav-theme-machine/tree/master/_demo/pages) to your `user/pages` directory. ii) You may check, whether cache is turned on. Otherwise turn it off for the moment and clear the cache (either via Admin panel) or by deleting the contents of the `cache` folder. iii) There are some typos you made and your page header in YAML format is not valid. Please double check.
3. This is may be more or less an issue with the **Admin plugin**. I don't know how to set a page template to the default ones selected. This can maybe done with a custom blueprint (but that requires advanced knowledge) and I actually don't know how to do it. If you think that's a pressing issue for you, I recommend you to open an issue in the [Admin plugin issue tracker](https://github.com/getgrav/grav-plugin-admin/issues).
4. Sorry, unfortunately I have no live example of a site with a comment to test. But I'm pretty sure, that you will find it on your own. Every webbrowser has a developer console i.e. Firefox `right-click -> inspect element`. You can then see the applied styles for the quote box and modify them. You can further have a look. All CSS files are located in [this folder](https://github.com/Sommerregen/grav-theme-machine/blob/master/assets/css/) and the e.g. the styling for the box is done [here](https://github.com/Sommerregen/grav-theme-machine/blob/master/assets/css/style.css#L472-L489). You just need to overwrite or modify those styles. Basically I recommend you to delete the background property for the [label](https://github.com/Sommerregen/grav-theme-machine/blob/master/assets/css/style.css#L481-L489) and use
   
   ``` css
   .item-in p {
   border: 2px solid #fff;
   margin: 0 auto;
   width: 74%;
   font-size: 1.4em;
   color: #a8a8a8;
   padding: 2.5em;
   line-height:1.5em;
   position: relative;
   }
   
   .item-in p:after {
   background: rgba(0, 0, 0, 0) url("http://www.sevensistersroad.com/user/themes/machine/assets/images/in.png") no-repeat scroll -4px 0;
   content: " ";
   height: 34px;
   left: 50%;
   margin-top: -5px;
   position: absolute;
   top: 100%;
   width: 25px;
   }
   ```
   
   instead.
