### ISSUE TITLE
Change the maximum width of the theme

### ISSUE THREAD

**Issue by herrdeh** [Sommerregen/grav-theme-machine#4]
On a 1280 screen, the theme looks very well. On my 1920 main monitor, it gets very broad, the text lines no longer are readable so well. How can I limit the maximum width the theme takes on the screen?

**Comment by Sommerregen** [comment]
This can be tackled via a CSS responsive media query like [style.css#L98](https://github.com/Sommerregen/grav-theme-machine/blob/develop/assets/css/style.css#L98) and restricting the body to a `max-width` value.

**Comment by herrdeh** [comment]
This does not work for me.
but in the style.css the expression "@media(max-width:" appears several times, with 1440px as highest value. 1440px, roughly estimated, could be the width the text takes on my screen.

So what else could I try?

**Comment by Sommerregen** [comment]
Hi @herrdeh ,

I just gave an example here. In your case you can add

```css
@media only screen and (min-width: 1440px) {
  .content {
    margin: 0 auto;
    max-width: 1300px;
  }
}
```

in the bottom of the `style.css`. I hope this gives you an idea. You may have to tweak it further.
