### ISSUE TITLE
Version mobile there is not  button in top-nav

### ISSUE THREAD

**Issue by Chrysweel** [Sommerregen/grav-theme-machine#8]
Hello.

In version mobile cannot see the button to display menu navbar.

Attached screenshots.

![machine-grav](https://user-images.githubusercontent.com/1416870/30785711-3cc13eaa-a16b-11e7-862f-a1c9544d2887.png)

The button exist ! 
![machine-grave-element](https://user-images.githubusercontent.com/1416870/30785713-3f7003fc-a16b-11e7-9314-be580ac9e4df.png)

**Comment by Sommerregen** [comment]
Oh, that's a `z-index` issue. I will fix it. Thanks for reporting! 👍 

**EDIT:** Actually it turns out, it is more than that. The whole menu icon is missing...

**Comment by LeftForSec** [comment]
any updates about this bug?

**Comment by fugo** [comment]
It is an error in `/themes/machine/assets/style.css` around line 90
```css
.top-nav span.menu:before{
	content: url(../images/menu.png)no-repeat 0px 0px;
	cursor:pointer;
	width:100%;
}
```
But it should be `content: url(../images/menu.png);` Thats it :wink: 

Edit:
Also line 85:
```css
.top-nav ul li a.active {
	color:#ffae00;
}
```
I change it to `color: Maroon;` or something similar or you can't see the **active** menu link
